package com.cnbs.recyclerviewdemo.utils;

/**
 * Created by Administrator on 2017/8/23.
 */

public class StrData {

    public static String indexStr = "{\"list\":[{\"code\":\"8002\",\"inputcode\":\"C\",\"name\":\"产科门诊\"},{\"code\":\"2008\",\"inputcode\":\"E\",\"name\":\"耳鼻喉科\"},{\"code\":\"6014\",\"inputcode\":\"E\",\"name\":\"儿科\"},{\"code\":\"8001\",\"inputcode\":\"F\",\"name\":\"妇科门诊\"},{\"code\":\"2046\",\"inputcode\":\"F\",\"name\":\"腹透中心\"},{\"code\":\"6013\",\"inputcode\":\"G\",\"name\":\"骨科\"},{\"code\":\"2023\",\"inputcode\":\"G\",\"name\":\"感染门诊\"},{\"code\":\"6015\",\"inputcode\":\"H\",\"name\":\"呼吸内科\"},{\"code\":\"2053\",\"inputcode\":\"K\",\"name\":\"康复科门诊\"},{\"code\":\"3011\",\"inputcode\":\"K\",\"name\":\"口腔科\"},{\"code\":\"6010\",\"inputcode\":\"M\",\"name\":\"泌尿外科\"},{\"code\":\"2019\",\"inputcode\":\"N\",\"name\":\"内分泌科\"},{\"code\":\"9001\",\"inputcode\":\"N\",\"name\":\"男科\"},{\"code\":\"3013\",\"inputcode\":\"P\",\"name\":\"皮肤科\"},{\"code\":\"6016\",\"inputcode\":\"R\",\"name\":\"乳腺疾病门诊\"},{\"code\":\"2002\",\"inputcode\":\"S\",\"name\":\"肾病内科\"},{\"code\":\"6009\",\"inputcode\":\"S\",\"name\":\"神经内科\"},{\"code\":\"2031\",\"inputcode\":\"S\",\"name\":\"神经外科\"},{\"code\":\"3000\",\"inputcode\":\"S\",\"name\":\"碎石门诊\"},{\"code\":\"3012\",\"inputcode\":\"S\",\"name\":\"烧伤整形科\"},{\"code\":\"2015\",\"inputcode\":\"T\",\"name\":\"透析中心\"},{\"code\":\"6012\",\"inputcode\":\"X\",\"name\":\"胸腹微创外科\"},{\"code\":\"6008\",\"inputcode\":\"X\",\"name\":\"消化内科\"},{\"code\":\"2029\",\"inputcode\":\"X\",\"name\":\"新生儿\"},{\"code\":\"6011\",\"inputcode\":\"X\",\"name\":\"心血管内科\"},{\"code\":\"6002\",\"inputcode\":\"Y\",\"name\":\"预防保健科\"},{\"code\":\"2009\",\"inputcode\":\"Y\",\"name\":\"眼科\"},{\"code\":\"2025\",\"inputcode\":\"Z\",\"name\":\"肿瘤专科\"},{\"code\":\"6007\",\"inputcode\":\"Z\",\"name\":\"中医科门诊\"}],\"code\":\"0\",\"msg\":\"当日挂号列表\"}";

    public static String mulitStr = "{\"list\":[{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-12 15:43:19.0\",\"memo\":\"\",\"surveyId\":1,\"title\":\"您对本次就诊的整体评价是：\",\"type\":0},{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-12 15:43:19.0\",\"memo\":\"\",\"surveyId\":2,\"title\":\"您对医务人员服务态度的评价：\",\"type\":0},{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-15 16:19:17.0\",\"memo\":\"\",\"surveyId\":3,\"title\":\"您对医疗效果或技术水平的评价：\",\"type\":0},{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-15 16:19:19.0\",\"memo\":\"\",\"surveyId\":4,\"title\":\"您对护理技术或护理服务的评价：\",\"type\":0},{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-20 17:54:38.0\",\"memo\":\"\",\"surveyId\":5,\"title\":\"您对医院后勤服务（保洁、保安、服务设施、食堂、洗涤等）的评价：\",\"type\":0},{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-20 18:42:43.0\",\"memo\":\"\",\"surveyId\":6,\"title\":\"您对本次诊疗费用的评价：\",\"type\":0},{\"choiceContenta\":\"非常满意\",\"choiceContentb\":\"满意\",\"choiceContentc\":\"一般\",\"choiceContentd\":\"不满意\",\"choiceContente\":\"非常不满意\",\"hospitalsId\":1,\"issueTime\":\"2017-06-27 10:00:34.0\",\"memo\":\"\",\"surveyId\":7,\"title\":\"除以上问题，您对医院其他方面的满意程度是：\",\"type\":0},{\"choiceContenta\":\"\",\"choiceContentb\":\"\",\"choiceContentc\":\"\",\"choiceContentd\":\"\",\"choiceContente\":\"\",\"hospitalsId\":1,\"issueTime\":\"2017-06-27 10:19:34.0\",\"memo\":\"\",\"surveyId\":8,\"title\":\"您对我们医院还有什么好的建议？如对某个医务人员提出特别表扬或批评，也请告诉我。\",\"type\":1}],\"code\":1,\"msg\":\"列表\"}";

}
